[[conservation-graphs]]
= Applying Graph Theory to Conservation Documentation

[abstract]
--
This section describes the analytical methods undertaken as part of doctoral research into the use of graph theoretical means to characterise, investigate, and analyse conservation graphs.  
--

// tag::introduction[]
This repo contains the datasets and scripts used as part of the doctoral research undertaken by Ana Tam.
The PhD was awarded by University of the Arts London (2023)
*Link to electronic copy of PhD*

// end::introduction[]

The folders in this repo contain datasets and scripts:

* <<conservation-graphs-datasets, The Datasets>>
* <<conservation-graphs-dataprep, Data Preparation>>
* <<conservation-graphs-phaseI, Phase I: Building a Conservation Knowledge Graph>>
* <<conservation-graphs-phaseII, Phase II: The Comparative Phase>>
* <<conservation-graphs-phaseIII, Phase III: Revised Knowledge Graph Building Method>>

[[conservation-graphs-datasets]]
== The Datasets

// tag::datasets[]
The datasets used can be found in the folder *Datasets*.  Where a dataset was derived from publically available sources, a link to the source is included.  However, there may be differences between the latest source versions and that used in this study (i.e. more recent versions, or they have not been prepared to work in this pipeline).  All scripts found in the Phase I, Phase II, and Phase III folders were written to work with the prepared datasets.  
// end::datasets[]

[[conservation-graphs-dataprep]]
== Data Preparation

// tag::dataprep[]
All scripts for loading data into Neo4j and analysing the graphs using Cypher can be found in each of the Phases folders.  The data extraction scripts for accessing the CAMEO and Discovery API data can be found in the Data Preparation folder.  
// end::dataprep[]

[[conservation-graphs-phaseI]]
== Phase I: Building a Conservation Knowledge Graph

// tag::phase1[]

// end::phase1[]

[[conservation-graphs-phaseII]]
== Phase II: The Comparative Phase

// tag::phase2[]

// end::phase2[]

[[conservation-graphs-phaseIII]]
== Phase III: Revised Knowledge Graph Building Method

// tag::phase3[]

// end::phase3[]
